language: ruby
rvm:
  - 1.9.3
notifications:
  email:
    - ddrinkard@sunlightfoundation.com
    - chris@nu7hat.ch
services:
  - mongodb
  - redis-server
before_script:
  - mongo datajam_test --eval 'db.addUser("travis", "test");'